#define FRONT_LEFT_ENCODER_PIN_A 32 
#define FRONT_LEFT_ENCODER_PIN_B 33 

#define FRONT_RIGHT_ENCODER_PIN_A 5
#define FRONT_RIGHT_ENCODER_PIN_B 4 

#define REAR_LEFT_ENCODER_PIN_A 26
#define REAR_LEFT_ENCODER_PIN_B 25

#define REAR_RIGHT_ENCODER_PIN_A 18
#define REAR_RIGHT_ENCODER_PIN_B 19


#define FRONT_LEFT_MOTOR_PIN_A 14
#define FRONT_LEFT_MOTOR_PIN_B 27

#define FRONT_RIGHT_MOTOR_PIN_A 21
#define FRONT_RIGHT_MOTOR_PIN_B 22

#define REAR_LEFT_MOTOR_PIN_A 12
#define REAR_LEFT_MOTOR_PIN_B 13

#define REAR_RIGHT_MOTOR_PIN_A 16
#define REAR_RIGHT_MOTOR_PIN_B 17

int encoderPins[4][2] = {
    {FRONT_LEFT_ENCODER_PIN_A, FRONT_LEFT_ENCODER_PIN_B},
    {FRONT_RIGHT_ENCODER_PIN_A, FRONT_RIGHT_ENCODER_PIN_B},
    {REAR_LEFT_ENCODER_PIN_A, REAR_LEFT_ENCODER_PIN_B},
    {REAR_RIGHT_ENCODER_PIN_A, REAR_RIGHT_ENCODER_PIN_B}
};

int motorPins[4][2] = {
    {FRONT_LEFT_MOTOR_PIN_A, FRONT_LEFT_MOTOR_PIN_B},
    {FRONT_RIGHT_MOTOR_PIN_A, FRONT_RIGHT_MOTOR_PIN_B},
    {REAR_LEFT_MOTOR_PIN_A, REAR_LEFT_MOTOR_PIN_B},
    {REAR_RIGHT_MOTOR_PIN_A, REAR_RIGHT_MOTOR_PIN_B}
};